### PR TITLE
The `v9` is for Brianna Ghey

### LINKED ISSUE #820: `DELETE` endpoints with `requestBody` leads to an OpenAPI semantic error
It looks like OpenAPI spec forbids a request body for `DELETE` operations:
- According to https://www.rfc-editor.org/rfc/rfc9110.html#name-delete:
> Although request message framing is independent of the method used, content received in a DELETE request has no generally defined semantics, cannot alter the meaning or target of the request, and might lead some implementations to reject the request and close the connection because of its potential as a request smuggling attack
- According to https://stackoverflow.com/a/54980985:
> No, you cannot use the OpenAPI 3.0 Specification and Swagger tools to implement DELETE requests with a request body

---
### Steps to reproduce:
- add endpoint with `delete` method like this:
```
defaultEndpointsFactory.build({
  methods: ["delete"],
  input: z.object({}),
...
```
- call `new OpenAPI({...}).getSpecAsYaml()`
- validate generated spec (e.g. on https://editor.swagger.io/)

### Actual behaviour:
There is a semantic error `DELETE operations cannot have a requestBody` in OpenAPI spec

### Expected behaviour
OpenApi spec generates without `requestBody` for DELETE operations

### PR DESCRIPTION
**Pull request by RobinTail**
image

> On 11 February 2023, Brianna Ghey, a 16-year-old British transgender girl from Birchwood in Warrington, Cheshire, England, was killed in Culcheth Linear Park in Culcheth, Warrington. Two accused teenagers, a boy and a girl both aged 15, are in police custody, having been charged with murder four days after the incident. A motive has not been established and police are investigating "all lines of inquiry", including investigating the killing as a possible hate crime

https://en.wikipedia.org/wiki/Killing_of_Brianna_Ghey

Closes #820

### CODE REVIEW

**Comment by RobinTail** [comment]
🚀  v9.0.0-beta1 released, tag `beta`

File: src/common-helpers.ts [hunk 1]
```diff
@@ -98,14 +100,18 @@ export function getMessageFromError(error: Error): string {
       )
       .join("; ");
   }
+  if (error instanceof OutputValidationError) {
+    const hasFirstField = error.originalError.issues[0].path.length > 0;
```
Comment (RobinTail) [inline src/common-helpers.ts:104]: `issues` actually may be empty.
need to handle this case

Comment (RobinTail) [reply src/common-helpers.ts]: fixed

**Comment by RobinTail** [comment]
🚀  v9.0.0-beta2 released, tag `beta`

**Comment by RobinTail** [comment]
🚀  v9.0.0-beta3 released, tag `beta`

**Comment by RobinTail** [comment]
Now I wanna do a cleanup and refactoring of `Endpoint` and remove `createApiResponse()`

File: src/client.ts [hunk 2]
```diff
@@ -46,14 +46,14 @@ export class Client {
...
+          schema: endpoint.getSchema("input"),
           isResponse: false,
         });
         const response = zodToTs({
           isResponse: true,
           schema: endpoint
-            .getPositiveResponseSchema()
-            .or(endpoint.getNegativeResponseSchema()),
+            .getSchema("positive")
+            .or(endpoint.getSchema("negative")),
```
Comment (RobinTail) [inline src/client.ts:56]: interesting...

**Review by RobinTail — COMMENTED** [review]
Nice, so far.

**Comment by RobinTail** [comment]
🚀 v9.0.0-beta4 released, tag beta

File: .github/workflows/codeql-analysis.yml [hunk 3]
```diff
@@ -13,10 +13,10 @@ name: "CodeQL"
 
 on:
   push:
-    branches: [ master, v7 ]
+    branches: [ master, v8 ]
```
Comment (RobinTail) [inline .github/workflows/codeql-analysis.yml:16]: v8 branch created

**Review by RobinTail — COMMENTED** [review]
should be fine 🤞🏽
