### PR TITLE
Issue 269: async refinements

### LINKED ISSUE #269: Async refinements
Hello,

First of all, thank you very much for your package!

I'm starting using it and I'm running into an issue. I have a piece of code that looks like this:
```ts
input: z.object({
        username: z.string().nonempty().max(100).refine(async username => {
            return await someAsyncFunction(username} == 0
       })
}),
```
I'm doing an async refinement, which should be allowed according to Zod docs. But I am getting this error:
`Async refinement encountered during synchronous parse operation. Use .parseAsync instead.`.

It looks like my `username` is not being parsed with parseAsync() but with parse(). Is the fact that we can't use async refinements on purpose?

### PR DESCRIPTION
**Pull request by RobinTail**
Closes #269

### CODE REVIEW

File: src/endpoint.ts [hunk 1]
```diff
@@ -231,7 +231,7 @@ export class Endpoint<
     const options: any = {};
     let isStreamClosed = false;
     for (const def of this.middlewares) {
-      input = { ...input, ...def.input.parse(input) }; // middleware can transform the input types
+      input = { ...input, ...(await def.input.parseAsync(input)) }; // middleware can transform the input types
       Object.assign(
```
Comment (RobinTail) [inline src/endpoint.ts:235]: Can use Object.assign() here as well. Might look prettier.

**Comment by RobinTail** [comment]
Should be fine.
