### PR TITLE
Fix: Availability of the proprietary schema definitions 

### LINKED ISSUE #952: Insufficient exports
_Originally posted by @McMerph in https://github.com/RobinTail/express-zod-api/discussions/951_

```
TS4023: Exported variable 'getFileStreamingEndpointsFactory' has or is using name 'ZodFileDef' from external module "{{some path}}/node_modules/.pnpm/express-zod-api@10.0.0_n5zqmeauuo4jduap7lnbjtm454/node_modules/express-zod-api/dist/index" but cannot be named.
```

since 10.0.0-beta1

### PR DESCRIPTION
**Pull request by RobinTail**
Closes #952 , related to #951 .

Making `ZodFileDef` and its siblings available for a reference when having `declaration: true` in consumer's tsconfig.

### CODE REVIEW

File: src/ez-namespace.ts
Comment (RobinTail) [inline src/ez-namespace.ts:1]: renamed to `src/proprietary-schemas.ts`

File: src/schema-walker.ts [hunk 1]
```diff
@@ -29,6 +34,12 @@ export type SchemaHandler<
   Variant extends HandlingVariant = "regular"
 > = (params: SchemaHandlingProps<T, U, Context, Variant>) => U;
 
+export type ProprietaryKinds =
```
Comment (RobinTail) [inline src/schema-walker.ts:37]: this one moved from `ez-namespace.ts` since it's only needed here.

File: src/proprietary-schemas.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { ZodDateIn } from "./date-in-schema";
+import { ZodDateOut } from "./date-out-schema";
+import { ZodFile } from "./file-schema";
+import { ZodUpload } from "./upload-schema";
+
+export type { ZodDateInDef } from "./date-in-schema";
+export type { ZodDateOutDef } from "./date-out-schema";
+export type { ZodFileDef } from "./file-schema";
```
Comment (RobinTail) [inline src/proprietary-schemas.ts:8]: should be available the following way:

```ts
type T = ez.ZodFileDef;
```

**Review by RobinTail — COMMENTED** [review]
Should be fine.
