### PR TITLE
Immutable `withMeta`

### LINKED ISSUE #827: OpenAPI spec generates extra examples if the output schema extends the input schema
### Steps to reproduce:
- Add test (e.g. at `tests/unit/open-api.spec.ts`):
```
test("should pass over the multiple examples of an object", () => {
  const zodSchema = z.object({ a: z.string() });
  const spec = new OpenAPI({
    config: sampleConfig,
    routing: {
      v1: {
        addSomething: defaultEndpointsFactory.build({
          method: "post",
          input: withMeta(zodSchema).example({ a: "first" }),
          output: withMeta(zodSchema.extend({ b: z.string() }))
            .example({ a: "first", b: "prefix_first" })
            .example({ a: "second", b: "prefix_second" }),
          handler: async ({ input: { a } }) => ({ a, b: `prefix_${a}` }),
        }),
      },
    },
    version: "3.4.5",
    title: "Testing Metadata:example on IO parameter",
    serverUrl: "http://example.com",
  }).getSpecAsYaml();
  expect(spec).toMatchSnapshot();
});
```
- Add snapshot (e.g. at `tests/unit/__snapshots__/open-api.spec.ts.snap`):
```
exports[`Open API generator Metadata should pass over the multiple examples of an object 1`] = `
"openapi: 3.0.0
info:
  title: Testing Metadata:example on IO parameter
  version: 3.4.5
paths:
  /v1/addSomething:
    post:
      responses:
        "200":
          description: POST /v1/addSomething Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      a:
                        type: string
                      b:
                        type: string
                    required:
                      - a
                      - b
                    example:
                      a: first
                      b: prefix_first
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      a: first
                      b: prefix_first
                example2:
                  value:
                    status: success
                    data:
                      a: second
                      b: prefix_second
        "400":
          description: POST /v1/addSomething Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      requestBody:
        content:
          application/json:
            schema:
              description: POST /v1/addSomething request body
              type: object
              properties:
                a:
                  type: string
              required:
                - a
            examples:
              example1:
                value:
                  a: first
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers:
  - url: http://example.com
"
`;
```
- run test

### Actual behaviour:
The above test fails because there are extra generated examples in the endpoint `requestBody`:
```
                  - a
                  examples:
                    example1:
                      value:
                        a: first
    +               example2:
    +                 value:
    +                   a: first
    +                   b: prefix_first
    +               example3:
    +                 value:
    +                   a: second
    +                   b: prefix_second
    +               example4:
    +                 value:
    +                   a: first
    +                   b: prefix_first
    +               example5:
    +                 value:
    +                   a: first
    +                   b: prefix_first
    +               example6:
    +                 value:
    +                   a: second
    +                   b: prefix_second
    +               example7:
    +                 value:
    +                   a: first
    +                   b: prefix_second
    +               example8:
    +                 value:
    +                   a: first
    +                   b: prefix_first
    +               example9:
    +                 value:
    +                   a: second
    +                   b: prefix_second
      components:
        schemas: {}
        responses: {}
        parameters: {}
        examples: {}
```

### Expected behaviour
The above test passes.

---
The workaround is to use
```
input: withMeta(zodSchema.extend({})).example(...
```
instead of
```
input: withMeta(zodSchema).example(...
```
So my guess is that the reason for this behaviour is that [withMeta mutates its argument](https://github.com/RobinTail/express-zod-api/blob/712560ca135da7fe08b11cb7bfacb1fb3070aa1c/CHANGELOG.md#L1218)

### PR DESCRIPTION
**Pull request by RobinTail**
Fixes #827

### CODE REVIEW

File: src/io-schema.ts [hunk 1]
```diff
@@ -40,13 +42,13 @@ export const getFinalEndpointInputSchema = <
...
     .map(({ input: schema }) => schema)
     .concat(input)
     .reduce((acc, schema) => acc.and(schema)) as ProbableIntersection<MIN, IN>;
   for (const middleware of middlewares) {
-    copyMeta(middleware.input, result);
+    result = copyMeta(middleware.input, result) as typeof result;
   }
-  copyMeta(input, result);
+  result = copyMeta(input, result) as typeof result;
   return result;
```
Comment (RobinTail) [inline src/io-schema.ts:53]: Can I do it more elegantly?

Comment (RobinTail) [reply src/io-schema.ts:53]: Moving copyMeta to reducer does not work the same way

File: src/metadata.ts [hunk 2]
```diff
@@ -32,20 +32,27 @@ type WithMeta<T extends z.ZodTypeAny> = MetaFixForStrippedObject<T> & {
...
-      example: {
-        get: (): ExampleSetter<T> => (value) => {
-          def[metaProp].examples.push(value);
-          return schema as WithMeta<T>;
-        },
+  return new This({ ...def }) as WithMeta<T>;
+};
+
+export const withMeta = <T extends z.ZodTypeAny>(schema: T): WithMeta<T> => {
+  const result = cloneSchemaForMeta<T>(schema);
```
Comment (RobinTail) [inline src/metadata.ts:43]: WithMeta on WithMeta makes redundant nesting that requires to be explicit.
Can I make it more smart?

File: src/metadata.ts [hunk 3]
```diff
@@ -32,20 +32,27 @@ type WithMeta<T extends z.ZodTypeAny> = MetaFixForStrippedObject<T> & {
...
+
+  Object.defineProperties(result, {
+    example: {
+      get: (): ExampleSetter<T> => (value) => {
+        const result2 = withMeta<T>(result);
```
Comment (RobinTail) [inline src/metadata.ts:48]: Naming

File: src/metadata.ts [hunk 4]
```diff
@@ -77,25 +84,24 @@ export const copyMeta = <A extends z.ZodTypeAny, B extends z.ZodTypeAny>(
...
-    def[metaProp].examples,
+  const result = withMeta(dest);
+  const examplesCombinations = combinations<B>(
+    result._def[metaProp].examples,
     src._def[metaProp].examples
   );
   // general deep merge except examples
-  def[metaProp] = mergeDeepRight(
-    { ...def[metaProp], examples: [] },
+  result._def[metaProp] = mergeDeepRight(
```
Comment (RobinTail) [inline src/metadata.ts:93]: this is actually not needed, since there is no other metadata besides examples

File: src/metadata.ts [hunk 5]
```diff
@@ -77,25 +84,24 @@ export const copyMeta = <A extends z.ZodTypeAny, B extends z.ZodTypeAny>(
...
     { ...src._def[metaProp], examples: [] }
   );
   if (examplesCombinations.type === "single") {
-    def[metaProp].examples = examplesCombinations.value;
+    result._def[metaProp].examples = examplesCombinations.value;
   } else {
     for (const [destExample, srcExample] of examplesCombinations.value) {
-      def[metaProp].examples.push(
+      result._def[metaProp].examples.push(
         mergeDeepRight({ ...destExample }, { ...srcExample })
```
Comment (RobinTail) [inline src/metadata.ts:102]: I think this function can be removed

File: src/result-handler.ts [hunk 6]
```diff
@@ -50,15 +50,15 @@ export const createResultHandler = <
...
+    let responseSchema = withMeta(
       z.object({
         status: z.literal("success"),
         data: output,
       })
     );
     for (const example of examples) {
       // forwarding output examples to response schema
-      responseSchema.example({
+      responseSchema = responseSchema.example({
```
Comment (RobinTail) [inline src/result-handler.ts:61]: Can I do it more elegantly?

File: src/metadata.ts (hunk 5 above)
Comment (RobinTail) [reply src/metadata.ts:102]: no, I actually can not

File: src/metadata.ts (hunk 4 above)
Comment (RobinTail) [reply src/metadata.ts]: fixed

File: src/metadata.ts (hunk 3 above)
Comment (RobinTail) [reply src/metadata.ts]: fixed

File: src/result-handler.ts (hunk 6 above)
Comment (RobinTail) [reply src/result-handler.ts]: fixed

File: src/io-schema.ts (hunk 1 above)
Comment (RobinTail) [reply src/io-schema.ts]: fixed

File: src/metadata.ts [hunk 7]
```diff
@@ -32,20 +32,26 @@ type WithMeta<T extends z.ZodTypeAny> = MetaFixForStrippedObject<T> & {
...
-      example: {
-        get: (): ExampleSetter<T> => (value) => {
-          def[metaProp].examples.push(value);
-          return schema as WithMeta<T>;
-        },
+  return new This({ ...def }) as WithMeta<T>;
+};
+
+export const withMeta = <T extends z.ZodTypeAny>(schema: T): WithMeta<T> => {
+  const copy = cloneSchemaForMeta(schema);
```
Comment (RobinTail) [inline src/metadata.ts:44]: here is the main question: is it a breaking change?

Comment (RobinTail) [reply src/metadata.ts:44]: yes, it's a behaviour changing of the public interface

File: src/metadata.ts [hunk 8]
```diff
@@ -32,20 +32,26 @@ type WithMeta<T extends z.ZodTypeAny> = MetaFixForStrippedObject<T> & {
...
+  const def = clone(schema._def) as MetaDef<T>;
   def[metaProp] = def[metaProp] || { examples: [] };
-  if (!("example" in schema)) {
-    Object.defineProperties(schema, {
-      example: {
-        get: (): ExampleSetter<T> => (value) => {
-          def[metaProp].examples.push(value);
-          return schema as WithMeta<T>;
-        },
+  return new This({ ...def }) as WithMeta<T>;
```
Comment (RobinTail) [inline src/metadata.ts:40]: ⚠️ Breaking

File: src/metadata.ts [hunk 9]
```diff
@@ -32,20 +32,26 @@ type WithMeta<T extends z.ZodTypeAny> = MetaFixForStrippedObject<T> & {
...
+  const def = clone(schema._def) as MetaDef<T>;
   def[metaProp] = def[metaProp] || { examples: [] };
-  if (!("example" in schema)) {
-    Object.defineProperties(schema, {
-      example: {
-        get: (): ExampleSetter<T> => (value) => {
-          def[metaProp].examples.push(value);
-          return schema as WithMeta<T>;
-        },
+  return new This(def) as WithMeta<T>;
```
Comment (RobinTail) [inline src/metadata.ts:40]: ⚠️ Breaking — behavior changing
