### PR TITLE
OpenAPI fix: avoid `nullable` when `type` is not present

### LINKED ISSUE #900: `z.record(z.any())` generates invalid OpenAPI spec
Hi, I've run into some trouble with OpenAPI spec generation of input and output payloads. My goal is to accept an arbitrary object as input. The way I've found that I can accomplish this is with `z.record(z.any())` and that works just fine functionality wise. The issue I run into is that when I generate the docs, I get the following YAML in the OpenAPI spec that's generated:

```yaml
type: object
additionalProperties:
  format: any
  nullable: true
```

When I check the validity of this using a tool like Redocly's CLI, I get the following error:

```
The `type` field must be defined when the `nullable` field is used.

687 |   additionalProperties:
688 |     format: any
689 |     nullable: true
```

From looking at the OpenAPI spec, this is an accurate error. I was wondering if there was a known workaround/better way to handle a schema field for accepting an arbitrary object. Just using `z.any()` results in the same error as above.

If I manually edit the spec and add `type: object` to the `additionalProperties`, the spec stops throwing that error. Here's an example:

```
type: object
additionalProperties:
  format: any
  nullable: true
  type: object
```

I'm wondering if this is an issue with spec generation, or if I'm just trying to tackle this problem the wrong way. If you have any advice on how I should be using Zod to accept an arbitrary object that passes the OpenAPI spec, I'd love to hear.

Thank you!

### PR DESCRIPTION
**Pull request by RobinTail**
Closes #900

### CODE REVIEW

File: src/open-api-helpers.ts [hunk 1]
```diff
@@ -688,16 +688,20 @@ export const depicters: HandlingRules<
...
   const shouldAvoidParsing = schema instanceof z.ZodLazy;
+  const hasTypePropertyInDepiction =
+    isSchemaObject(current) && current.type !== undefined;
   const examples = shouldAvoidParsing ? [] : getExamples(schema, isResponse);
   return {
     ...(description && { description }),
     ...(!shouldAvoidParsing &&
+      hasTypePropertyInDepiction &&
       schema.isNullable() &&
       !(isResponse && hasCoercion(schema)) && { nullable: true }),
```
Comment (RobinTail) [inline src/open-api-helpers.ts:706]: I wanna make it nicer

File: tests/unit/__snapshots__/open-api.spec.ts.snap [hunk 2]
```diff
@@ -4037,7 +4032,6 @@ paths:
           description: GET /v1/getSomething parameter
           schema:
             format: string (preprocessed)
-            nullable: true
```
Comment (RobinTail) [inline tests/unit/__snapshots__/open-api.spec.ts.snap:4040]: should mention this in the changelog as well

File: src/open-api-helpers.ts (hunk 1 above)
Comment (RobinTail) [reply src/open-api-helpers.ts]: done

File: src/open-api-helpers.ts [hunk 3]
```diff
@@ -688,18 +688,25 @@ export const depicters: HandlingRules<
...
-export const onEach: Depicter<z.ZodTypeAny, "last"> = ({
+export const onEach: Depicter<z.ZodTypeAny, "each"> = ({
   schema,
   isResponse,
+  current,
 }) => {
   const { description } = schema;
   const shouldAvoidParsing = schema instanceof z.ZodLazy;
+  const hasTypePropertyInDepiction =
+    isSchemaObject(current) && current.type !== undefined;
```
Comment (RobinTail) [inline src/open-api-helpers.ts:699]: if it's a reference (somehow) we should not add any additional props to it

Comment (RobinTail) [reply src/open-api-helpers.ts]: done

**Review by RobinTail — COMMENTED** [review]
Need a specific test

File: tests/unit/__snapshots__/open-api.spec.ts.snap (hunk 2 above)
Comment (RobinTail) [reply tests/unit/__snapshots__/open-api.spec.ts.snap:4040]: done

**Review by RobinTail — COMMENTED** [review]
Ready
